
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - demo.devops.kubesphere
  resources:
  - demoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.devops.kubesphere
  resources:
  - demoes/status
  verbs:
  - get
  - patch
  - update
